pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
        maven {
            name "Fabric"
            url "https://maven.fabricmc.net/"
        }
        maven {
            name "KikuGie Releases"
            url "https://maven.kikugie.dev/releases"
        }
        maven {
            name "KikuGie Snapshots"
            url "https://maven.kikugie.dev/snapshots"
        }
    }
}

plugins {
    id "dev.kikugie.stonecutter" version "0.9.6"
    id "dev.kikugie.loom-back-compat" version "0.3"
}

stonecutter {
    // Configuration goes here
    // The root project is the Tree
    create(rootProject) {
        versions("1.21.11", "26.1")
        vcsVersion = "26.1"
    }
}